-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 06, 2025 at 09:51 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `scholarfindsdb`
--

-- --------------------------------------------------------

--
-- Table structure for table `accounts`
--

CREATE TABLE `accounts` (
  `user_id` int(4) NOT NULL,
  `date_joined` date NOT NULL,
  `archived` tinyint(1) NOT NULL DEFAULT 0,
  `role` varchar(10) NOT NULL DEFAULT 'regular',
  `username` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(25) NOT NULL,
  `personalization` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `accounts`
--

INSERT INTO `accounts` (`user_id`, `date_joined`, `archived`, `role`, `username`, `name`, `email`, `password`, `personalization`) VALUES
(1, '0000-00-00', 0, 'superadmin', 'Renzjan', 'Renzjan Moncinilla', 'renzjan.moncinilla@umak.edu.ph', 'dev01@umak', 'RJ-'),
(2, '0000-00-00', 0, 'superadmin', 'Andrei', 'Paul Andrei Valencia', 'paul.valencia@umak.edu.ph', 'dev02@umak', ''),
(3, '0000-00-00', 0, 'superadmin', 'Dhanica', 'Ma. Dhanica Ballesteros', 'ma.ballesteros@umak.edu.ph', 'dev03@umak', ''),
(4, '0000-00-00', 0, 'superadmin', 'Lilxianaze', 'Lilxianaze Garcia', 'lilxianaze.garcia@umak.edu.ph', 'dev04@umak', ''),
(5, '0000-00-00', 0, 'superadmin', 'Superadmin Faculty', 'sa@umak', 'sa@umak', 'sa@umak', ''),
(6, '0000-00-00', 0, 'admin', 'Admin Faculty', 'a@umak', 'a@umak', 'a@umak', '');

-- --------------------------------------------------------

--
-- Table structure for table `accounts_backup`
--

CREATE TABLE `accounts_backup` (
  `user_id` int(4) NOT NULL,
  `date_joined` date NOT NULL,
  `archived` tinyint(1) NOT NULL DEFAULT 0,
  `role` varchar(10) NOT NULL DEFAULT 'regular',
  `username` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(25) NOT NULL,
  `personalization` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `theses`
--

CREATE TABLE `theses` (
  `thesis_id` int(4) NOT NULL,
  `archived` tinyint(1) NOT NULL DEFAULT 0,
  `published_date` varchar(7) NOT NULL,
  `course` varchar(100) NOT NULL,
  `category` varchar(20) NOT NULL,
  `title` varchar(150) NOT NULL,
  `authors` varchar(255) NOT NULL,
  `adviser` varchar(100) NOT NULL,
  `abstract` varchar(1500) NOT NULL,
  `keywords` varchar(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `theses`
--

INSERT INTO `theses` (`thesis_id`, `archived`, `published_date`, `course`, `category`, `title`, `authors`, `adviser`, `abstract`, `keywords`) VALUES
(1, 0, '2006', 'BSCNA', 'Project Proposal', 'Asian Institute of Management - Upgrading of Storage System', 'Bautista, Joseph, et al.', 'Obra, Eduardo', '', ''),
(2, 0, '2009', 'BSCS-AD', 'Research Project', 'Development of a Web Phone Cam Application', 'Culala, Donalyn V., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(3, 0, '2009', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF HIGH LEVEL ACCESS SECURITY SYSTEM', 'Matienzo, Victor, et al.', 'Dr. Sabado, Danilo C.', '', ''),
(4, 0, '2009', 'BSCS-AD', 'Research Project', 'UNIVERSITY OF MAKATI FACULTY EVALUATION SYSTEM (UMak FES)', 'Damian, Jessa P., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(5, 0, '2010', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF ReciPedia: RECIPES ENCYCLOPEDIA', 'Magnaye, Sarah Jane S., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(6, 0, '2010', 'BSCS-AD', 'Research Project', 'Interactive System of the Animal World', 'De Chavez, Diana R., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(7, 0, '2010', 'BSCS-AD', 'Research Project', 'MACES (Makati Consortium for Educational Scholars) Portal', 'Balbuena, Cristine Juneth R., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(8, 0, '2010', 'BSCS-AD', 'Research Project', 'MAKATI CITY PUBLIC SCHOOLS MEDICAL AND DENTAL SERVICES INTEGRATED RECORDS MANAGEMENT AND INVENTORY SYSTEM', 'Javier, Maria Kristine V., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(9, 0, '2010', 'BSCS-AD', 'Research Project', 'The Acropolis Condominium Management System', 'Amor, Jefferson D., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(10, 0, '2010', 'BSCS-AD', 'Research Project', 'UNIVERSITY OF MAKATI OJT PORTAL', 'Guliban, Joanne B., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(11, 0, '2011', 'BSCS-AD', 'Research Project', 'A Development of Security Profile System for Philippine National Police', 'Arcigal, Bernadeth Mae, et al.', 'Dr. Sabado, Danilo C.', '', ''),
(12, 0, '2011', 'BSCS-AD', 'Research Project', 'AUTOMATED STUDENT ATTENDANCE MONITORING SYSTEM USING RADIO FREQUENCY IDENTIFICATION (RFID)', 'Alfonso, Alfred Allan A., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(13, 0, '2011', 'BSCS-AD', 'Research Project', 'BIO-SMS DOOR LOCK SYSTEM', 'Gamit, Jonathan J., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(14, 0, '2011', 'BSCS-AD', 'Research Project', 'CITEG: CIPHER TEXT AND STEGO IMAGE GENERATOR', 'Tamanio, Richard Dean R., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(15, 0, '2011', 'BSCS-AD', 'Research Project', 'CLAMP 1.0: A Constitutional Law Mobile Application', 'Abuda, Darlie M., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(16, 0, '2011', 'BSCS-AD', 'Research Project', 'C-Security Ware Assistant for 32-Bit and 64-Bit Microsoft Windows Operating System', 'Razal, John Michael T., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(17, 0, '2011', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF A WEB-BASED ENTRANCE EXAMINATION SYSTEM WITH CAREER ASSESSMENT FOR UNIVERSITY OF MAKATI', 'Guemo, Irish Joyce L., et al.', '', '', ''),
(18, 0, '2011', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF CARMA: A CARTOGRAPHIC MAKER', 'Diamante, Arthur F., et al.', '', '', ''),
(19, 0, '2011', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF DRIVING SKILLS AND PERFORMANCE SIMULATOR', 'Padilla, Mhendelson C., et al.', '', '', ''),
(20, 0, '2011', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF GEEK: GAME FOR EDUCATIONAL ENHANCEMENT OF KIDS', 'Lavides, Maryvic Amor L.', '', '', ''),
(21, 0, '2011', 'BSCS-AD', 'Research Project', 'Development of ICount - an Integrated POS and Inventory System', 'Chan, April Mae G., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(22, 0, '2011', 'BSCS-AD', 'Research Project', 'DEVELOPMENT of Makati Mapping System', 'Nava, Adonis M., et al.', '', '', ''),
(23, 0, '2011', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF MICROPROFESSOR: COMPUTER AIDED INSTRUCTION IN GENERAL SCIENCE', 'Barbosa, John Rey B., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(24, 0, '2011', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF NIHONGO FORMAL TRAINER USING VOICE RECOGNITION', 'Ibardo, Hanzel John C., et al.', '', '', ''),
(25, 0, '2011', 'BSCS-AD', 'Research Project', 'Development of Race Result Manager Using Radio-Frequency Identification', 'David, Marie Cris D., et al.', '', '', ''),
(26, 0, '2011', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF READING PROFICIENCY TEST SOFTWARE', 'Gerodias, Jesusa Ma. Clara N., et al.', '', '', ''),
(27, 0, '2011', 'BSCS-AD', 'Research Project', 'EARTH ANGEL: AN ENVIRONMENTAL 2D GAME', 'Mariñas, Jemelyn D., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(28, 0, '2011', 'BSCS-AD', 'Research Project', 'GENERIC POINT OF SALE WITH INVENTORY SYSTEM', 'Aniceto, Mary Rick C., et al.', '', '', ''),
(29, 0, '2011', 'BSCS-AD', 'Research Project', 'KULTURA: A Talking Dictionary Mobile Application', 'Aguilar, Julie Ann B., et al.', '', '', ''),
(30, 0, '2011', 'BSCS-AD', 'Research Project', 'Petfille - Online Dog Care Products 3D Catalog Application', 'Tulio, Jerome D., et al.', '', '', ''),
(31, 0, '2011', 'BSCS-AD', 'Research Project', 'SMS Controlled Home Appliances Management System', 'Escarilla, Krizhel A., et al.', '', '', ''),
(32, 0, '2011', 'BSCS-AD', 'Research Project', 'SPMO LAN-Based Inventory of I.T. Materials Sytem Using Barcode Reader', 'Candelaria, Manly A., et al.', '', '', ''),
(33, 0, '2011', 'BSCS-AD', 'Research Project', 'UMAK LIBRARY SYSTEM', 'Calvelo, Jihan C., et al.', '', '', ''),
(34, 0, '2011', 'BSCS-AD', 'Research Project', 'UMAK OnPreS: University of Makati Online Pre-registration System', 'Makilan, John Ferry M., et al.', '', '', ''),
(35, 0, '2012', 'BSCNA', 'Project Proposal', 'A PROJECT PROPOSAL OF WI-FI CONNECTIVITY FOR THE CITY OF MAKATI', 'Abanto, Alvin L., et al.', 'Dechavez, Anna Charisma F.', '', ''),
(36, 0, '2012', 'BSCNA', 'Project Proposal', 'A WI-FI PROPOSAL FOR THE CITY OF MAKATI WITH UNIVERSITY OF MAKATI AS MAIN DISTRIBUTOR', 'Aldeguer, Manuel Jr., et al.', 'Dechavez, Anna Charisma F.', '', ''),
(37, 0, '2012', 'BSCNA', 'Thesis', 'A DESIGN PROPOSAL FOR MAKING MAKATI A WI-FI CITY', 'Berame, Rafael, et al.', 'Rico, Ramil P.', '', ''),
(38, 0, '2012', 'BSCNA', 'Thesis', 'A NETWORK PROJECT DESIGN IMPLEMENTATION IN TRANSFORMING MAKATI CITY AS THE PHILIPPINES FIRST WIFI CITY', 'Katon, Ralph A., et al.', 'Rico, Ramil P.', '', ''),
(39, 0, '2012', 'BSCNA', 'Thesis', 'A PROJECT PROPOSAL ON MAKATI CITY WIDE WIRELESS NETWORK CONNECTION', 'Abiar, Arnel V. Jr. et al.', 'Rico, Ramil P.', '', ''),
(40, 0, '2012', 'BSCNA', 'Thesis', 'A WI-FI PROJECT PROPOSAL FOR THE CITY OF MAKATI', 'Alcontin, Marby P., et al.', '', '', ''),
(41, 0, '2012', 'BSCNA', 'Thesis', 'A WIRELESS NETWORK DESIGN FOR MAKATI CITY', 'Bersamina, Mark Noney A., et al.', '', '', ''),
(42, 0, '2012', 'BSCNA', 'Thesis', 'Enabling Wi-Fi for the City of Makati', 'Basa, Michael John, et al.', '', '', ''),
(43, 0, '2012', 'BSCNA', 'Thesis', 'Free Wi-Fi Demand for Public Involvement: A Proposal for Municipal Wireless Network', 'Bernadas, Ma. Angeline V., et al.', '', '', ''),
(44, 0, '2012', 'BSCNA', 'Thesis', 'PROPOSED DESIGN FOR THE IMPLEMENTATION OF A WI-FI ZONE COMMUNITY IN THE CITY OF MAKATI', 'Buena, Jeanbing D., et al.', '', '', ''),
(45, 0, '2012', 'BSCNA', 'Thesis', 'WIFI FOR THE WHOLE CITY OF MAKATI', 'Alita, Albert P., et al.', '', '', ''),
(46, 0, '2012', 'BSCNA', 'Thesis', 'WIRELESS MAKATI', 'Aranil, Michael boy P.', '', '', ''),
(47, 0, '2012', 'BSCNA', 'Thesis', 'WIRELESS NETWORK FOR THE CITY OF MAKATI', 'Abayari, John Antonio B., et al.', '', '', ''),
(48, 0, '2012', 'BSCNA', 'Thesis', 'WIRELESS NETWORK FOR THE CITY OF MAKATI', 'Ching, Mark Daniel S., et al.', '', '', ''),
(49, 0, '2012', 'BSCNA', 'Thesis', 'WIRELESS NETWORK FOR THE CITY OF MAKATI', 'Antonio, Quinno S., et al.', '', '', ''),
(50, 0, '2013', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF GAME OF THE GENERALS', 'Babaran, Karla Mae B., et al.', '', '', ''),
(51, 0, '2013', 'BSCS-AD', 'Research Project', 'Juan and the Enchanted Creatures: A Desktop Arcade Game', 'Rocillo, Pearl Rose, et al.', '', '', ''),
(52, 0, '2013', 'BSCS-AD', 'Research Project', 'PINOY CHECKERS INTERACTIVE GAME USING BLUETOOTH CONNECTION', 'Buenaobra, Wilcon Marie B., et al.', '', '', ''),
(53, 0, '2013', 'BSIT-NS', 'Research Project', 'AGENTWORKS ONLINE APPLICATION WITH AUTO-PROFILING SYSTEM', 'Angeles, Lorenzo E., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(54, 0, '2014', 'BSCNA', 'Project Proposal', 'Design and Implementation of a Domain Controller with File Server and Remote Access for all Colleges of University of Makati', 'Padilla, Carlo, et al.', 'Pangan, Shirley', '', ''),
(55, 0, '2014', 'BSCNA', 'Project Proposal', 'Design and Implementation of Data Center for University of Makati and Makati Science High School', 'Cantuba, Jessa Mae G., et al.', 'Olivo, Michael C.', '', ''),
(56, 0, '2014', 'BSCNA', 'Project Proposal', 'Implementation of a Secured Network Infrastructure as an Avenue of the Learning Management System in the University of Makati', 'Samonte, Angelito D., et al.', 'Olivo, Michael C.', '', ''),
(57, 0, '2014', 'BSCNA', 'Project Proposal', 'Implementation of Structured Cabling with Server Management and Establish Internet Connection in E-room, Library and Computer Laboratory of San Jose E', 'Acopra, Ruben S., et al.', '', '', ''),
(58, 0, '2014', 'BSCNA', 'Project Proposal', 'Implementation of Wireless Local Area Network with Web Filtering and Print Monitoring using K9 Web Protection and Print Inspector for Vynex Signs Phil', 'Alon, Alon, Crizzan, et al.', '', '', ''),
(59, 0, '2014', 'BSCNA', 'Project Proposal', 'Network Infrastructure Support with High-Speed Internet Connection Intended for use of Cloud-Based Learning Management System', 'Bontia, Arvin Jonn C., et al.', '', '', ''),
(60, 0, '2014', 'BSCNA', 'Project Proposal', 'Project Rachis: Interconnectivity of the Network Infrastructure of the University of Makati by Developing the Backbone Cabling System', 'Matoto, Joseph G., et al.', '', '', ''),
(61, 0, '2014', 'BSCNA', 'Project Proposal', 'Propose a server 2012 and upgrading the network with CCTV for the Development Academy of the Philippines (DAP)', 'Hubilla, Crystal Jean, et al.', '', '', ''),
(62, 0, '2014', 'BSCNA', 'Project Proposal', 'Propose and Design Structured Cabling System for BSIT-NS Corporation - ITS Department', 'Angelo, Weigehte Mae, et al.', '', '', ''),
(63, 0, '2014', 'BSCNA', 'Project Proposal', 'Rehabilitation of East Rembo Elementary School Computer Laboratory: Implementing the TIA/EIA 568C Structured Cabling System Standard and Managing the ', 'Almariego, Joebel, et al.', '', '', ''),
(64, 0, '2014', 'BSCNA', 'Project Proposal', 'REHABILITATION ON THE SERVER ROOM OF ONE OUTSOURCE DIRECT CORPORATION: IMPLEMENTING THE ANSI/TIA/EIA 606-B AND 569 STANDARDS', 'Batiforra, Stephanie Kaye, et al.', '', '', ''),
(65, 0, '2014', 'BSCNA', 'Project Proposal', 'Renovate the Network Infrastructure with a Structured Cabling Standards and Server Installation and Administration for BUY&SELL Philippines', 'Baria, Vina T., et al.', '', '', ''),
(66, 0, '2014', 'BSCNA', '', 'Data Center in Accordance to ANSI-TIA 942 Standard for Public High School Interconnectivity in City of Makati', 'Derilo, Arvin, et al.', 'Pangan, Shirley', '', ''),
(67, 0, '2014', 'BSIT-NS', 'Research Project', 'DEVELOPMENT OF GENERIC IT QUIZBEE SYSTEM', 'Polancos, Marjourie R., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(68, 0, '2017', 'BSIT-NS', 'Feasibility Project', 'ANDAR: Android Natural Disaster Alert Response', 'Andrade, Jomiel H., et al.', 'Asejo, Nelson R.', '', ''),
(69, 0, '2018', 'BSCNA', 'Capstone Project', 'DESIGN AND IMPLEMENTATION OF NETWORK INFRASTRUCTURE FOR DHL DAVAO', 'Badion, Mc. Chrise, et al.', 'Sabado, Wilber B., MM', '', ''),
(70, 0, '2018', 'BSCNA', 'Capstone Project', 'IMPLEMENTATION OF VIRTUAL PRIVATE NETWORK IN OIL INDUSTRY MANAGEMENT BUREAU AND ENHANCEMENT OF WIDE AREA NETWORK IN DEPARTMENT OF ENERGY', 'Agullana, Alpha Genesis, et al.', 'Asejo, Nelson A., MIT, FRIIT', '', ''),
(71, 0, '2018', 'BSCNA', 'Capstone Project', 'IMPLEMENTING DYNAMIC MULTIPOINT (VPN) ACROSS DIFFERENT BARANGAYS OF MAKATI CITY', 'Arnaiz, Jesryl V., et al.', 'Dasig, Daniel Jr., Ph. D.', '', ''),
(72, 0, '2018', 'BSCNA', 'Capstone Project', 'NETWORK SERVICES ENHANCEMENT OF IT-AUDIT DEPARTMENT IN MEGAWORLD CORPORATION', 'Alegre, Randyl Wayne D., et al.', 'Gabriel, Jarby DC., GC-IMD', '', ''),
(73, 0, '2018', 'BSCNA', 'Capstone Project', 'SITE TO SITE COMMUNICATION USING MULTI-PROTOCOL LABEL SWITCHING LAYER 3 VIRTUAL PRIVATE NETWORK SERVICES IMPLEMENTATION TO WENPHIL CORPORATION\'S NETWO', 'Mendoza, Ronnel C., et al.', 'Ortiz, RJay L.', '', ''),
(74, 0, '2018', 'BSCNA', 'Case Study', 'NETWORK INFRASTRUCTURES OF COMPOSITE WING SAVINGS AND LOAN ASSOCIATION INC., EAGLE FINANCIAL SERVICES GROUP INC., EQUIPMENT ENGINEERING INC. GOLF ASIA', 'II-BCNA', 'Arcalas, Lilibeth H., M.Sc.', '', ''),
(77, 0, '2018', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF ALEX: A WEB-BASED HOTEL VOICE ASSISTANT AND RESERVATION SYSTEM', 'Talon, Gemma A., et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(78, 0, '2018', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF BOI MEDIC: A FIRST AID TUTORIAL SIMULATION MOBILE APPLICATION', 'Yanoc, Gregory Peter D., et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(79, 0, '2018', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF CHUM: AN ANDROID MOBILE APPLICATION FOR EMOTIONAL WELLNESS', 'Clemente, Angelika B., et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(80, 0, '2018', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF ITRACK: A UMAK EMPLOYEE MOBILE MONITORING SYSTEM', 'Sabado, Romil P., et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(81, 0, '2018', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF MOBILE GREGG SHORTHAND TUTORIAL', 'Abejar, George Louise DV., et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(82, 0, '2018', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF OPM KARAOKE MOBILE APPLICATION', 'Badayos, Bernadette Aimee B., et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(83, 0, '2018', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF SHOOTYM: AN ASPIRING MODEL SOCIAL MEDIA APPLICATION', 'Grajo, Maralee N.', 'Dr. Sabado, Danilo C.', '', ''),
(84, 0, '2018', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF STEPJOB: AN EMPLOYMENT AID MOBILE APPLICATION', 'Tan, Michelle T., et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(85, 0, '2018', 'BSCS-AD', 'Research Project', 'DEVELOPMENT OF VETOPIA: AN ONLINE VETERINARY CLINIC MANAGEMENT SYSTEM', 'Manzano, Wesley John O., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(86, 0, '2018', 'BSCS-AD', 'Research Project', 'PROJECT KASAYSAYAN: THE PATRIOTISM OF RIZAL (VIRTUAL REALITY)', 'Belo, Keirwin H., et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(87, 0, '2018', 'BSCS-AD', 'Thesis', 'A QUEUING THEORY ANALYSIS IMPROVEMENT MEASURE FOR OUTPATIENT DEPARTMENT PROCESS', 'Arduo, Jonathan R., et al.', 'Mansueto, Christian Michael M.', '', ''),
(88, 0, '2018', 'BSCS-AD', 'Thesis', 'A STUDY ON THE EFFICIENCY OF WAVELET PITCH ESTIMATION ALGORITHM', 'Romero, Nichole John T., et al.', 'Mansueto, Christian Michael M.', '', ''),
(89, 0, '2018', 'BSCS-AD', 'Thesis', 'AN ALGORITHM ANALYSIS FOR OPTIMIZED SEARCH IN LOCATION INTELLIGENT SYSTEM', 'Sunga, Pushyaida Aira C., et al.', 'Pahayahay, Alexander B.', '', ''),
(90, 0, '2018', 'BSCS-AD', 'Thesis', 'AN ANALYSIS OF ASYNCTASK THREAD POOLING IN A MOBILE INTEGRATED ENVIRONMENT', 'Teves, Romel M., et al.', 'Asejo, Nelson R.', '', ''),
(91, 0, '2018', 'BSCS-AD', 'Thesis', 'An Analysis of Dijkstra\'s Algorithm in a Navigation App for Visually Impaired Person', 'Marayan, Hazel S., et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(92, 0, '2018', 'BSCS-AD', 'Thesis', 'AN ANALYSIS OF K-MEANS ALGORITHM FOR FILE TRANSFER IN A WIRELESS ENVIRONMENT', 'Aguero, Al John T., et al.', 'Diampoc, Lester G.', '', ''),
(93, 0, '2018', 'BSCS-AD', 'Thesis', 'AN ANALYSIS OF LINEAR CONGRUENTIAL GENERATOR FOR PSEUDO RANDOM GENERATION OF QUESTIONNAIRES OF THE ALZH AID APP', 'Nilo, Kyle Harley L., et al.', 'Asejo, Nelson R.', '', ''),
(94, 0, '2018', 'BSCS-AD', 'Thesis', 'COMPARATIVE ANALYSIS OF MYSQL AND FIREBASE IN A MOBILE APPLICATION', 'Velasquez, John Darnel D., et al.', 'Asejo, Nelson R.', '', ''),
(95, 0, '2018', 'BSCS-AD', 'Thesis', 'NAIVE FORECASTING ALGORITHM ANALYSIS FOR STUDENT GRADE PREDICTION', 'Panti, Enrique Jimmar C., et al.', 'Alar, Hernan S.', '', ''),
(96, 0, '2018', 'BSCS-AD', 'Thesis', 'QUEUEING THEORY ANALYSIS AS AN IMPROVEMENT MEASURE FOR ORDERING PROCESSES', 'Villaver, Ray Vincent Phillip D., et al.', 'Cortez, Rex Jayson T.', '', ''),
(97, 0, '2018', 'BSCS-AD', 'Thesis', 'SCHEDULE OPTIMIZATION OF EDUCATOR\'S ACTIVITIES THROUGH EVOLUTIONARY PROGRAMMING', 'Labrador, Aldwin B., et al.', 'Alar, Hernan S.', '', ''),
(98, 0, '2018', 'BSCS-AD', 'Thesis', 'THE EFFICIENCY OF CONVOLUTIONAL NEURAL NETWORKS FOR LEAF PATTERN RECOGNITION', 'Bigcal, Richard N., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(99, 0, '2018', 'BSCS-AD', 'Thesis', 'THE EFFICIENCY OF DELTA TIME RENDER UPDATE IN AN ISOMETRIC MOBILE AND DESKTOP-BASED GAME APPLICATION', 'Galvan, Rosalie P., et al.', 'Asejo, Nelson A.', '', ''),
(100, 0, '2018', 'BSCS-AD', 'Thesis', 'THE EFFICIENCY OF HUB-BASED LABELING ALGORITHM FOR AN EMERGENCY RESPONSE MOBILE APPLICATION', 'Bacani, Sarah Joy J., et al.', 'Dorin, Rommel L.', '', ''),
(101, 0, '2018', 'BSCS-AD', 'Thesis', 'THE EFFICIENCY OF IMPLEMENTING A* ALGORITHM FOR ENEMY AI PATHFINDING IN A VIRTUAL REALITY GAME', 'Dulay, Kennyjay O., et al.', 'Mansueto, Christian Michael M.', '', ''),
(102, 0, '2018', 'BSCS-AD', 'Thesis', 'THE EFFICIENCY OF REAL-TIME CODE MERGING ALGORITHM FOR DISTRIBUTED PROGRAMMING', 'Taligatos, Kim Justine M., et al.', 'Cortez, Rex Jayson T.', '', ''),
(103, 0, '2018', 'BSCS-AD', '', 'DEVELOPMENT OF GEOCALCULATOR: GEOMETRY AUTOMATIC CALCULATOR MOBILE APPLICATION', 'Manalo, Jemuel P., et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(104, 0, '2018', 'BSCS-AD', '', 'DEVELOPMENT OF PHASES.IO: A PROJECT MANAGEMENT TOOL WITH RESOURCE CONTROL REPOSITORY', 'Mojares, Ely Nell Jireh L. Jr., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(105, 0, '2018', 'BSCS-AD', '', 'DEVELOPMENT OF POT (Plant On Track): AN ARDUINO-BASED PLANT GROWTH MONITORING SYSTEM', 'Sanchez, Michelle Joy T., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(106, 0, '2018', 'BSCS-AD', '', 'DEVELOPMENT OF REVEAL: RIO DE JANEIRO VIRTUAL EXPERIENCE AND LEARNING MOBILE APPLICATION', 'Espinosa, Mhervin P.', 'Dr. Sabado, Danilo C.', '', ''),
(107, 0, '2018', 'BSCS-AD', '', 'DEVELOPMENT OF SIGNCON: A SIGN LANGUAGE-TO-SPEECH APPLICATION FOR MUTE PEOPLE', 'Pablo, Jerald Jon, et al.', 'Dr. Sabado, Danilo C.', '', ''),
(108, 0, '2018', 'BSCS-AD', '', 'DEVELOPMENT OF SIRKIT: A BASIC ELECTRICAL WIRING SIMULATOR ON ANDROID', 'Apuya, Jaybert Noli P. II, et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(109, 0, '2018', 'BSCS-AD', '', 'DEVELOPMENT OF UMAK KONEK: AN ACADEMIC SOCIAL NETWORKING PLATFORM', 'Pangan, Jenree Robert S., et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(110, 0, '2018', 'BSCS-AD', '', 'DEVELOPMENT OF VAST: VIRTUAL APPLICATION FOR SOLAR SYSTEM TOUR', 'Gamboa, John Nichol C., et al.', 'Dr. Sabado, Danilo C.', '', ''),
(111, 0, '2018', 'BSCS-AD', '', 'MULTIPLE INTELLIGENCES ASSESSMENT APPLICATION', 'De Leon, Richard V., et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(112, 0, '2018', 'BSCS-AD', '', 'THE DEVELOPMENT OF WEBEE: AN INTERACTIVE ANDROID LEARNING APPLICATION OF HTML LANGUAGE FOR KIDS', 'Retales, Eugene J., et al.', 'Congzon, Janice Pola D., MIT', '', ''),
(113, 0, '2018', 'BSIT-NS', 'Feasibility Project', 'A FEASIBILITY STUDY ON IPAWNMO: ONLINE PAWNSHOP MANAGEMENT SYSTEM', 'Padilla, Krizza N., et al.', 'Gannaban, Era Marie F., MIT', '', ''),
(114, 0, '2018', 'BSIT-NS', 'Feasibility Project', 'DEVELOPMENT OF EKADEMYA: AN ONLINE LEARNING PLATFORM', 'Evangelista, Mark Joshua C., et al.', 'Tadeo, Cecilia E., Ph. D.', '', ''),
(115, 0, '2018', 'BSIT-NS', 'Feasibility Project', 'E-PARKING MANAGEMENT SYSTEM USING RFID FOR THE UNIVERSITY OF MAKATI', 'Iquina, Mikaela M., et al.', 'Tadeo, Cecilia E., Ph. D.', '', ''),
(116, 0, '2018', 'BSIT-NS', 'Feasibility Project', 'LAKBAY: A MOTORPOOL MANAGEMENT SYSTEM', 'Buljatin, Jerald Mark T., et al.', 'Tadeo, Cecilia E., Ph. D.', '', ''),
(117, 0, '2018', 'BSIT-NS', 'Feasibility Project', 'LOGISTICS MANAGEMENT SYSTEM FOR JEXSAN LOGISTICS PHILIPPINES INC.', 'Espiritu, Angelica P., et al.', 'Tadeo, Cecilia E., Ph. D.', '', ''),
(118, 0, '2018', 'BSIT-NS', 'Feasibility Project', 'ONLINE MEDICAL MANAGEMENT SYSTEM FOR KLINIKAYA MEDICAL SPECIALISTS INC.', 'Merie, Joseph E., et al.', 'Tadeo, Cecilia E., Ph. D.', '', ''),
(119, 0, '2018', 'BSIT-NS', 'Feasibility Project', 'PARISH CHURCH MANAGEMENT SYSTEM FOR MARY MIRROR OF JUSTICE PARISH', 'Agcaoili, Jonathan M., et al.', 'Tadeo, Cecilia E., Ph. D.', '', ''),
(120, 0, '2018', 'BSIT-NS', 'Feasibility Project', 'PLANET DRUGSTORE PHARMACY MANAGEMENT SYSTEM', 'Lauriano, JV B., et al.', 'Tadeo, Cecilia E., Ph. D.', '', ''),
(121, 0, '2018', 'BSIT-NS', 'Feasibility Project', 'STUDENT ELECTION E-VOTING SYSTEM (SEEVS)', 'Lumang, Ralph Jomar M., et al.', 'Tadeo, Cecilia E., Ph. D.', '', ''),
(122, 0, '2018', 'BSIT-NS', 'Feasibility Project', 'URGUIDE: GUIDANCE AND COUNSELING MANAGEMENT SYSTEM', 'Ariado, Patrick Justin L., et al.', 'Tadeo, Cecilia E., Ph. D.', '', ''),
(123, 0, '2018', 'BSIT-NS', 'Feasibility Project', 'WEB APPLICATION FOR PAYROLL MANAGEMENT SYSTEM', 'Adolfo, Janmar R., et al.', 'Tadeo, Cecilia E., Ph. D.', '', ''),
(124, 0, '2018', 'BSIT-NS', 'Feasibility Study', 'PANGLAO OASIS MIDRISE CONDOMINIUM PROPERTY RESERVATION SYSTEM', 'Dasig, Rizalyn Joy A., et al.', 'Asejo, Nelson A.', '', ''),
(125, 0, '2018', 'BSIT-NS', 'Feasibility Study', 'UNIVERSITY EVENT MANAGEMENT SYSTEM', 'Apostol, Ivylyn P., et al.', 'Tadeo, Cecilia E., Ph. D.', '', ''),
(126, 0, '2023', 'BSCS-AD', 'Thesis', 'A SENTIMENT ANALYSIS OF FEEDBACKS OPTIMIZING LOGISTIC REGRESSION', 'Bumatay, Brix C., et al.', '', '', ''),
(127, 0, '2023', 'BSCS-AD', 'Thesis', 'CHATERON: THE DEVELOPMENT OF ENROLLMENT CHATBOT FOR UNIVERSITY OF MAKATI USING BIDIRECTIONAL ENCODER REPRESENTATIONS FROM TRANSFORMERS', 'Dela Cruz, Jenn Rose, et al.', 'Dellosa, Daniel P.', '', ''),
(128, 0, '2023', 'BSCS-AD', 'Thesis', 'DEVELOPMENT OF SWIFTLY: AN ONLINE REAL-TIME AIR QUALITY MONITORING SYSTEM UTILIZING FUZZY LOGIC ALGORITHM', 'Abello, Trisha A., et al.', 'Plan, Jomariss B., MSIT', '', ''),
(129, 0, '2023', 'BSCS-AD', 'Thesis', 'EDUKIDS: UTILIZING SHUFFLING ALGORITHM IN BUILDING SENTENCES', 'Alba, Washington A. Jr., et al.', 'Cruz, Edgardo T., MIT', '', ''),
(130, 0, '2023', 'BSCS-AD', 'Thesis', 'I-Recognize- A Mobile Application for Image Recognition of Geometrical Figures for Kids Age 4 to 5 Utilizing Convolutional Neural Network', 'Dumaran, Yuri A., et al.', 'Ramos, Ethel A., MSIT, MSCS', '', ''),
(131, 0, '2023', 'BSCS-AD', 'Thesis', 'RECOTIRE: A WEB-BASED TIRE QUALITY ANALYSIS & RECOMMENDATION SYSTEM USING RANDOM FOREST ALGORITHM', 'Bautista, Raven B., et al.', 'Pahayahay, Alexander B., MIT', '', ''),
(132, 0, '2023', 'BSCS-AD', 'Thesis', 'THE DEVELOPMENT OF FOODTHRIFT: AN E-COMMERCE WEB APPLICATION UTILIZING NAIVE BAYES CLASSIFIER ALGORITHM', 'Bartolome, Kea, et al.', 'Dorin, Rommel L., MIT', '', ''),
(133, 0, '2023', 'BSIT-NS', 'Capstone', 'A Proposed Enhancement of Network Infrastructure and Network Security for Prospr PH', 'Delmendo, Zcire Lance T., et al.', '', '', ''),
(134, 0, '2023', 'BSIT-NS', 'Capstone', 'A Proposed Network Infrastructure Enhancement for Runto Technology Inc. Using High Availability Technology and ADDS', 'Estira, Ronan B., et al.', '', '', ''),
(135, 0, '2023', 'BSIT-NS', 'Capstone', 'A PROPOSED SITE-TO-SITE IPSEC VPN WITH INTRUSION DETECTION SYSTEM FOR PINNACLE REAL ESTATE CONSULTING SERVICES, INC.', 'Estrella, Steven Russell S., et al.', '', '', ''),
(136, 0, '2023', 'BSIT-NS', 'Capstone', 'A Proposed Wide Area Network (WAN) Infrastructure in Securing Network and Data for Erovoutika Robotics and Automation Solutions', 'Estrada, Alliyah Loubert SJ., et al.', '', '', ''),
(137, 0, '2023', 'BSIT-NS', 'Capstone', 'A PROPOSED WIDE AREA NETWORK DESIGN FOR TOBY\'S SPORTS MAIN AND REGIONAL CENTER UTILIZING SD-WAN IPSEC TUNNELING WITH ZERO TRUST ARCHITECTURE', 'Jimenez, Scott Glenn B., et al.', '', '', ''),
(138, 0, '2023', 'BSIT-NS', 'Capstone', 'DEVELOPMENT OF A WEB-BASED INVENTORY MANAGEMENT SYSTEM FOR PROPERTY AND DISPOSAL IN THE DEPARTMENT OF SUPPLY AND PROPERTY MANAGEMENT OFFICE (SPMO) AT ', 'Parina, Aldrin V., et al.', '', '', ''),
(139, 0, '2023', 'BSIT-NS', 'Capstone', 'DEVELOPMENT OF A WEB-BASED PAYROLL SYSTEM USING ADVANCED ENCRYPTION STANDARD (AES) AS DATA ENCRYPTION ALGORITHM FOR PANCIT NG TAGA MALABON', 'Mora, Joshua T., et al.', '', '', ''),
(140, 0, '2023', 'BSIT-NS', 'Capstone', 'Development of an Online Shopping System Exclusive for Partner Vendors of Safe House - Tagkayawan, Quezon', 'Andres, Aeron Jonh L., et al.', '', '', ''),
(141, 0, '2023', 'BSIT-NS', 'Capstone', 'Development of Attendance System for the Barangays of Makati', 'Cornelio, John Maozen S., et al.', '', '', ''),
(142, 0, '2023', 'BSIT-NS', 'Capstone', 'Development of Cloud-Based Ordering and Inventory Monitoring Web System Utilizing AES Encryption Algorithm as Security for Smart Polar Tube Ice Inc.', 'Laspoña, Vincent C., et al.', '', '', ''),
(143, 0, '2023', 'BSIT-NS', 'Capstone', 'Development of Employee Management System for Eco-Hotel', 'Serafin, Aljun P., et al.', '', '', ''),
(144, 0, '2023', 'BSIT-NS', 'Capstone', 'Development of Faculty Evaluation System for Fort Bonifacio Senior High School', 'Ada, Noime Q., et al.', '', '', ''),
(145, 0, '2023', 'BSIT-NS', 'Capstone', 'DEVELOPMENT OF GPS - BASED ACCIDENT ALERT SYSTEM FOR MILKWEED TRICYCLE OPERATORS AND DRIVERS\' ASSOCIATION (MILTODA)', 'Manabat, Ivan L., et al.', '', '', ''),
(146, 0, '2023', 'BSIT-NS', 'Capstone', 'Development of Patient Appointment Information System (PAIS) for Ospital Ng Makati', 'Cunanan, Jericho P., et al.', '', '', ''),
(147, 0, '2023', 'BSIT-NS', 'Capstone', 'Development of RFID-based Students Attendance System', 'Corral, Hannah L., et al.', '', '', ''),
(148, 0, '2023', 'BSIT-NS', 'Capstone', 'Development of Sherlock:  A Phishing Detection in Email Content utilizing Machine Learning Algorithms', 'Andes, Eussell Joy V., et al.', '', '', ''),
(149, 0, '2023', 'BSIT-NS', 'Capstone', 'Development of Social Services Assistance System for the office of Makati Social Welfare Department', 'Abejar, Argielene Mae C., et al.', '', '', ''),
(150, 0, '2023', 'BSIT-NS', 'Capstone', 'DEVELOPMENT OF SSS: STUDENT SECURITY SYSTEM WITH STUDENT ATTENDANCE AND HEALTH MONITORING SYSTEM FOR FORT BONIFACIO HIGH SCHOOL', 'De Vera, John Carlo M., et al.', '', '', ''),
(151, 0, '2023', 'BSIT-NS', 'Capstone', 'DEVELOPMENT OF WEB-BASED ATTENDANCE MONITORING SYSTEM USING MULTI-FACTOR BIOMETRIC FOR BARANGAY COMEMBO', 'Agreda, Efren III B., et al.', '', '', ''),
(152, 0, '2023', 'BSIT-NS', 'Capstone', 'INTEGRATING IN-LINE FIREWALL, HYPERVISOR SECURITY AND CRYPTOGRAPHIC STRATEGIES FOR DATA CENTER VIRTUALIZATION OF DEPARTMENT OF ENERGY', 'Eugenio, Gian Carlo E., et al.', '', '', ''),
(153, 0, '2023', 'BSIT-NS', 'Capstone', 'THE DEVELOPMENT OF MATATAGVPN: AN APPLICATION OF ETHEREUM BLOCKCHAIN IN CREATING DECENTRALIZED VIRTUAL PRIVATE NETWORK', 'Castillano, Nicole Ann R., et al.', '', '', ''),
(154, 0, '2023', 'BSIT-NS', 'Capstone', 'The Development of SynerTech: A Cloud-Based Rendering Service Website Utilizing Hybrid Encryption Algorithm for Data Security', 'Laranjo, Jean Leslie N., et al.', '', '', ''),
(155, 0, '2023', 'BSIT-NS', 'Capstone', 'Web-Based Barangay Management Information System Using Web Application Firewall', 'Aban, Kaye Nichole C., et al.', '', '', ''),
(156, 0, '2023', 'Diploma in Application Development', 'Special Project', 'E-Barangay System for Pembo, Makati City', 'Flores, Pamela P., et al.', '', '', ''),
(157, 0, '2023', 'Diploma in Application Development', 'Special Project', 'Juan Faith Adventure - Travel Booking System', 'Corda, Ryan P., et al.', '', '', ''),
(158, 0, '2023', 'Diploma in Application Development', 'Special Project', 'Lucas Tailor: Tailoring Management System', 'Critica, Prince Charles L., et al.', '', '', ''),
(159, 0, '2023', 'Diploma in Application Development', 'Special Project', 'Quintin De Borja Health Center Appointment System', 'Mendoza, Elijah James, et al.', '', '', ''),
(160, 0, '2023', 'Diploma in Application Development', 'Special Project', 'TEMPO RENTAL: A WEB BASED CAR RENTAL SYSTEM', 'Carianga, Jomarie Matthew G., et al.', '', '', ''),
(161, 0, '2023', 'Diploma in Application Development', 'Special Project', 'The Fitness Ave. Gym Management System', 'Arroyo, Matthew Joseph P., et al.', '', '', ''),
(162, 0, '2024-04', 'BSCS-AD', 'Thesis', 'CST HUB: A WEB-BASED APPLICATION SYSTEM FOR STYLE FORMATTING ANALYSIS OF UMAK CS THESIS MANUSCRIPT USING COMPOSITE RULE-BASED ALGORITHM', 'MHIKE LAURENCE N. LACONSAY-HENSON S. BUNAYOG-RAPHAEL JORREL H. DOCOT-CHASTINE JOY B. SANQUI-AIA A. VALLES', '', 'This study focuses on developing a system for style formatting analysis of UMak CS Thesis Manuscripts using Composite Rule-Based Algorithm by utilizing Python Libraries such as PyMuPDF, and Tesseract OCR. The system consists of calculating bounding boxes to check the formatting of CS thesis papers, providing a valuable tool for students and professors to efficiently review and reduce formatting errors. The method involves calculating PDF paper size, margins, spacings and defining fonts. Using Tesseract OCR and PyMuPDF, the system extracts text details, detects margins, and calculates text spacings. The model detects the errors by highlighting them with OpenCV specifically fonts, margins, and spacing. Despite difficulties in manual data extraction and time-consuming margin and spacing detection, the developed system proves useful in improving UMak CS Thesis Manuscript formatting, resulting with an overall accuracy rate of 90.66% across various formatting components specifically: margin, spacings, and font-related, with a potential for future refinements. Furthermore, the system evaluation reached an overall rating of 3.55, indicating a general acceptance among Computer Science (CS) students and professors.', 'Style Formatting Analysis, Formatting Errors, Composite Rule-based Algorithm, UMak CS Thesis Manuscripts, Text Extraction, Data extraction.'),
(163, 0, '2024-05', 'BSIT-NS', 'Capstone', 'A PROPOSED NETWORK SECURITY FOR MARB PRINTING SERVICES', 'ARANETA, JAN LORRY F. - BUENAOBRA, KENNETH JR. I. - DELA VEGA, JOANNE R.', '', 'This study addresses the cybersecurity challenges faced by MARB Printing Services and proposes a network security to enhance protection against cyber threats. The objective is to propose a network security encompassing physical, network, and application security measures for the future expansion of the company. The methodology involves enhancing the existing network with Sophos XG Firewall, Sophos XG XDR, and an improved network layout. Utilizing Cisco devices like routers, switches, and network cabling, along with configuring firewalls, VLAN, RIP, TCP, and WAN, ensures security of critical and confidential information, maintaining the company\'s operational stability. Additionally, Windows Server 2022 is recommended for centealized user management and secure file storage. Results indicate that both IT professionals and employees, achieving a composite evaluation mean of 4.04, indicating strong agreement on its effectiveness. Key outcomes include better identification and mitigation of security flaws, enhanced data protection, and efficient traffic management. The continuous surveillance and proactive measures, such as regular alerts and training, contribute to building trust among clients and partners. Recommendations include designing for future expansion, collaborating with cybersecurity experts, adopting new technologies, and developing a comprehensive incident response plan to maintain and enhance security measures as the cybersecurity landscape evolves.This study serves ', 'Cybersecurity challenges, Network security, Physical security measures, Network security measures, Application security measure.'),
(164, 0, '2024-05', 'BSIT-NS', 'Capstone', 'A PROPOSED OF SECURED WIDE AREA NETWORK USING IPSEC VIRTUAL PRIVATE NETWORK FOR ALPHA PLUS PROPERTY HOLDINGS CORPORATION', 'MARIYHELA DENNISE P. CHAN - BRYAN JOSHUA B. MANANSALA - MARK EDSON H. ROMARATE', '', 'The proposal focused on the enhancement of the network security of Alpha Plus Property Holdings Corporation by implementing a secured Wide Area Network (WAN) using IPsec Virtual Private Network (VPN) technology. The solution involves deploying IPsec VPN for site-to-site and remote access connections, integrating Fortinet security solutions and Google Workspace Business Plus for improved collaboration. The implementation plan includes comprehensive testing to ensure enhanced security, improved performance, and streamlined communication. The proposal aims to provide reliable network infrastructure tailored to the corporation\'s needs, by utilizing VMWare Workstation, Windows Server 2022, Fortinet FortiGate Firewall, and Cisco Packet Tracer. In compliance with ISO/IEC 27001 standards are emphasized to ensure information security and effective risk management, with the deployed network elements serving as crucial protectors of valuable data and enabling authorized access exclusively. The proposed solution will enhance threat detection and incident response, conduct security audits and vulnerability assessments, and improve the overall security and efficiency of Alpha Plus Property Holdings Corporation\'s network infrastructure, thereby reducing the risk of data breaches and cyber-attacks.', '(WAN) Wide area network, (IPsec VPN) Internet Protocol Security Virtual Private Network, (ISO/IEC 27001) international standard for information securi'),
(165, 0, '2024-05', 'BSIT-NS', 'Capstone', 'A PROPOSED WAN INFRASTRUCTURE DESIGN USING AN ALTERNATIVE NEXT-GENERATION FIREWALL UTILIZING SD-WAN AND IPSEC VPN FOR NEW WORLD DIAGNOSTICS (NWD)', 'TOLOSA, ROD VINCE M. - BREGIAS, MARK JOHN M. - SIBAL, JASPER L.', '', 'This study examines an alternative next-generation firewall for New World Diagnostics which has the same features and functionalities such as SD-WAN and IPsec VPN, while being more economically viable and suitable to the needs of the organization. This study\'s topic arose as the organization\'s current next-generation firewall costs exceeded what the organization was comfortable with, therefore looking for another option. This study will be a testbed and a proposal for a new alternative next-generation firewall and a few tweaks and improvements to the current network design. Incorporating related literature and studies enabled the researchers to possess more insight, understanding, and knowledge in the undertaking of this study\'s completion. Simulations and tests were also done on the proposed network designs, particularly the local area network (LAN) and the wide area network (WAN) for basic functionalities such as VLANs and DHCP to more complex features such as SD-WAN and IPsec VPN. Finally, the proposed network design was evaluated by IT specialists and users from New World Diagnostics, this enabled the researchers to have a holistic evaluation and review of the proposal, and also support its integrity. This study\'s results proved that alternative next-generation firewalls suited the needs of organizations similar to New World Diagnostics with top-of-the-line features such as SD-WAN and IPsec VPN. Equipped with specifications that are much more in line with the size and nee', 'Network Infrastructure Design, Wide Area Network (WAN), Local Area Network (LAN), Software Defined Wide Area Network (SD-WAN), IPsec VPN, Next-Generat'),
(166, 0, '2024-05', 'BSIT-NS', 'Capstone', 'A PROPOSED WEB APPLICATION WITH CLOUD-BASED SECURITY FOR INTEGRATIVE LEARNING CONTENT-BASED SYSTEM FOR SENIOR HIGH SCHOOL STUDENTS OF PRESIDENT DIOSDA', 'ORMIDO, JOHN MARK M. - PAZ, JHET CHRISTIAN V. - VIVO, SARAH ERICA D.', '', 'This paper helps you understand and know how to develop an online learning management system from the base with the cloud-based security that is reinforced for an additional layer of security for the system which can give peace of mind to the users of the developed project. With the help of the standards that we are utilizing and using nowadays such as AICC, SCORM, API, and cmi5, the developers successfully developed an online learning management system which is for President Diosdado Macapagal High School, this project is addressing the issues of the users of the President Diosdado Macapagal High School like missing requirements, not accurate recordings, missing paper works and many more. Based on the of the results and summary of findings that has the researchers gathered from testing and interviews, the performance efficiency, the PDMHS-LMS gets a weighted average mean of 4.21, compatibility testing also gets a staggering value of 4.2 weighted average mean. In terms of usability, the PDMHS-LMS has the weighted average mean of 4.31, lastly, reliability, reliability gets a 4.20 weighted average mean. In conclusion the proposed technology PDMHS-LMS is effective and reliable as an alternative solution for the existing problems that is in the President Diosdado Macapagal High School, with this and backed-up by the research results from the interview and research that the researchers performed.', 'Learning management system, cloud security, database, administrator, ISO 25010, modules, dashboard, web-based application, server, database, switches,'),
(167, 0, '2024-05', 'BSIT-NS', 'Capstone', 'A WEB-BASED BARANGAY RESIDENT INFORMATION SYSTEM', 'ARAZA, ASHLEY TRAVIS - CATIG, CESAR B. JR. - TOBIAS, JAN EARL M.', '', 'In order to address the difficulty that has been affecting the barangay North Signal in Taguig City, the goal of this study is to offer a solution. The strategy involved developing a digital information system for the barangay to serve as a tool for addressing manual processes. A web-based system known as the Barangay Information System is equipped with functionalities for storing, processing, generating, and managing resident\'s information. The system ensures the security of the system through the implementation of authorization, employing a one-time password (OTP) for additional layer of security to authenticate users during login, ensuring that only the legitimate account holder can perform actions or access sensitive information. Information was properly protected utilizing encryption, decryption and data backup mechanisms, including reCAPTCHA for validating users distinguishing between bots and humans. To develop an information management system, the proponents utilized the PHP programming language. Furthermore, this generate an online backup of the user\'s information to maintain data integrity that assures the information of the users are stored securely within the system. This significantly optimize the management of residence documents and information for Barangay North Signal residents. The research acknowledged that the system has limitations, such as security in biometrics, online transactions, and chatbot. Overall, the research indicates that implementing a web-ba', 'Resident Information System, Web-based, PHP, reCAPTCHA, OneTime Password, Encryption and Decryption, Backup, Digital, North Signal, Taguig City.'),
(168, 0, '2024-05', 'BSIT-NS', 'Capstone', 'ASIAN HOSPITAL HEALTH DATA HUB: DEVELOPMENT OF RESEARCH INFORMATION SYSTEM FOR ASIAN HOSPITAL', 'BUENO, REVIN R. - GENERAO, JONAS G. - MEJILLANO, BEA BIANCA R.', '', 'The Hospital Research Information System is a web-based software application tailored for Asian Hospital aimed at modernizing and enhancing the research process within the institution. The Hospital Research Information System aims to digitize and optimize research workflows within Asian Hospital. By leveraging technology, the hospital aims to overcome challenges associated with manual processes. The research design for developing a research information system for Asian Hospital adopts a descriptive approach to address its research process challenges. The study begins with an introduction outlining the need for Enhanced effectiveness and optimized user satisfaction in the research process. A literature review explores successful implementations and challenges faced by similar systems in research settings providing insights to inform the de development process. The study evaluated the web systems functionality, reliability, usability, and security and the results showed that the web system has excellent performance and usability and is reliable and secure. Results of testing reveal that research is reliably recorded and kept in the database and the website is compatible with a range of devices and browsers assuring easy accessibility and operation. And lastly, the results of the evaluation that the Asian Hospital Health Data Hub has been effective in addressing the demands of Asian Hospital needs.', 'Hospital Research Information System, Asian Hospital Health Data Hub'),
(169, 0, '2024-05', 'BSIT-NS', 'Capstone', 'DESIGNING A SCALABLE AND FLEXIBLE NETWORK ARCHITECTURE FOR MANDALUYONG COLLEGE OF SCIENCE AND TECHNOLOGY WITH INTER-VLAN ROUTING AND ETHERCHANNEL BUND', 'BUSTILLO, PAUL NATHAN P. - CHUA, JULIUS S. - ROCHA, NATHANIEL GLENN M.', '', 'As digital technologies rapidly expand, educational institutions must innovate with strong network infrastructures to support diverse academic and administrative activities. This capstone project addresses the unique challenges faced by Mandalyong College of Science and Technology (MCST), a new institution with a direct internet connection.    This network setup makes MCST vulnerable to cyberattacks and unreliable internet connections. To address these issues, the researchers proposed a comprehensive network architecture to enhance MCST\'s connectivity, redundancy, scalability, and security. The project focuses on developing a scalable and flexible network infrastructure integrating Inter-VLAN Routing and    EtherChannel Bundling Technology, aiming to establish a resilient and adaptable network for current and future needs. Key objectives include optimizing the local area network, vast area network, server management, and network security using tools like Cisco Packet Tracer and GNS3, aligning with ISO 27001:2022 standards. The study used a Likert Scale to evaluate Organizational Control, Physical Control, Technological Control, Redundancy, Scalability, and Reliability, yielding positive results from evaluators. Successful testing validated the proposed project\'s functionality and reliability. This project enhances MCST\'s network infrastructure, providing practical insights and methodologies for newly established institutions. It lays a resilient foundation for the future grow', 'Digital Technology, Network Infrastructure, Cyberattacks, Redundancy, Scalability, Inter-VLAN Routing, EtherChannel Bundling, Digital technologies'),
(170, 0, '2024-05', 'BSIT-NS', 'Capstone', 'DEVELOPING AN ONLINE ADMISSION SYSTEM FOR MANDALUYONG COLLEGE OF SCIENCE AND TECHNOLOGY', 'BALBUENA, RON ALVIN O. - LAMADORA, MICHELLE IRISH L. - ROC, ROSELYN F.', '', 'Online Admission System is a web-based software application that helps to automate and simplify the process of admitting students into educational institutions such as schools, colleges, and universities. Mandalyong College of Science and Technology is a newly opened educational institution located in Mandalyong City, Philippines. This school currently carries out the admissions process manually and faces challenges managing the increasing number of applicants using Google Forms, which raises concerns about data security and privacy. This study aims to develop an Online Admission System for Mandaluyong College of Science and Technology to replace the traditionally manual process of admission, which can be time-consuming, prone to errors and lacks adequate security measures. The proposed system offers a secure and user-friendly online admission system with features such as content management, data analytics, and two-factor authentication. This system can help the school automate administrative tasks related to admissions, such as managing applications and applicant data.The method used in this study is Agile Methodology. This method is popular in the IT industry known for its adaptability and flexibility in responding to user needs.The evaluation results showed strong agreement with 83.33% rating the system\'s accuracy, ease of use, reliability, and security in managing applications and applicant data. The findings showed that the researchers successfully developed an online ad', 'Admission System, Online Admission System, Online Examination System'),
(171, 0, '2024-05', 'BSIT-NS', 'Capstone', 'DEVELOPING AN ONLINE REGISTRATION SYSTEM FOR MANDALUYONG COLLEGE OF SCIENCE AND TECHNOLOGY', 'DACUYCUY, JOSEPH WILLIAM G. - DORONILA, DENISE CLAIRE B.', '', 'Online Registration System is a web-based software application that helps to automate and simplify the process of admitting students into educational institutions such as schools, colleges, and universities. Mandalyong College of Science and Technology is a newly opened educational institution located in Mandaluyong City, Philippines. This school currently carries out the admissions process manually and faces challenges managing the increasing number of applicants using Google Forms, which raises concerns about data security and privacy. This study aims to develop an Online Registration System for Mandaluyong College of Science and Technology to replace the traditional manual process of registration, and lessen the use load of papers which can be time-consuming, prone to errors, and lack adequate security measures. The proposed system offers a secure and user-friendly online registration system with features such as management of contents for administrators, registrar, and end-users for students. This system can help the school automate tasks related to registration, such as managing applications and applicant data. The method used in this study is Agile Methodology. This method is popular in the IT industry known for its adaptability and flexibility in responding to user needs. The evaluation results showed strong agreement with \"4.02 over 5\" rating the system\'s accuracy, functionality, performance efficiency, compatibility, usability, reliability, security, maintainability,', 'Online Registration System, Mandalyong College of Science and Technology, Admissions, Registration, Agile Methodology, Authenticated'),
(172, 0, '2024-05', 'BSIT-NS', 'Capstone', 'DEVELOPMENT OF A WEB-BASED SEXUALITY EDUCATION PLATFORM FOR ADOLESCENTS', 'BENITEZ, TRIXIE MAY C. - GARCIA, JAHMEL ANDRE C. - GRAMATICA, JULIUS A.', '', 'This paper explores the development and evaluation of a web-based platform for sexuality education, aimed at addressing the lack of comprehensive sexuality education materials in educational institutions. Chapter 1 delves into the background of the issue, highlighting the challenges faced in implementing comprehensive sexuality education in the Philippines. Chapter 2 reviews related literature, providing insights from various studies on sexuality education, online resources, and the effectiveness of web-based programs. In Chapter 5, the study\'s findings, conclusions, and recommendations are presented. The findings indicate that the developed web-based platform performed well in terms of performance efficiency, usability, security, functionality, and maintainability, as evaluated based on ISO 25010 standards. Conclusions drawn from the study emphasize the importance of web-based tools in delivering comprehensive sexuality education and the need for continuous improvement in such platforms. Recommendations include adding a summative test and implementing a certification system to enhance student learning and engagement. Overall, this study contributes to addressing the challenges in providing comprehensive sexuality education through innovative technological solutions.', 'Web-based Sexuality Education, Sexuality Education Platform, Learning Management System');
INSERT INTO `theses` (`thesis_id`, `archived`, `published_date`, `course`, `category`, `title`, `authors`, `adviser`, `abstract`, `keywords`) VALUES
(173, 0, '2024-05', 'BSIT-NS', 'Capstone', 'DEVELOPMENT OF BRIGHT BYTE: A WEB-BASED APPLICATION FOR TEETHTALK DENTAL CLINIC', 'CARMONA, SID NATHAN F. - CARPIO, ELSA P. - NONO, MARK ANGELO D.', '', 'The dentistry sector is always striving to enhance its efficiency and care quality. The goal of this study was to create a web application for TeethTalk dental clinic that includes basic dental clinic management system functions like patient information management and easy access to dental/medical history, as well as advanced features like data cleaning and deduplication, data analytics, and two-factor authentication. The application\'s purpose was to identify and eliminate unnecessary entries from the system, as well as improve data quality and accuracy during information display via interactive dashboard visualizations. The research design used by the researchers is design thinking approach which promotes innovation, empathy, and continuous problem-solving, enabling the development of user-centered solutions that effectively address complex challenges. The approach focused on detecting dirty data and duplications that could not be captured by the traditional method used by receptionists and dentists. It is an important approach for cleaning dirty data and identifying duplications, enabling the researchers to identify inaccurate data. The methodology of the study also includes the data flow diagrams as well as the testing and evaluation procedures that will be used to assess the system\'s overall functionality. This study used a diverse strategy to analyze Bright Byte\'s influence on dentistry clinic operations. First, the study investigated the usefulness data analytics module', 'Data cleaning, data deduplication, data analytics, two-factor authentication'),
(174, 0, '2024-05', 'BSIT-NS', 'Capstone', 'DEVELOPMENT OF FACILITIES AND EQUIPMENT MANAGEMENT SYSTEM FOR BARANGAY SANTOL', 'ABUNDO, PRECIOUS APPLE DINI-AY, JONALYN S. - TUSING, LAWRENCE JOHN P.', '', 'The capstone project titled \"Development of Facilities and Equipment Management System for Barangay Santol\" seeks to revolutionize asset management by addressing the urgent need for an efficient tracking and management system for barangay assets, encompassing buildings, equipment, and vehicles. The primary goal is to design and implement a robust, user-friendly system that empowers barangay officials to monitor assets, schedule maintenance, plan replacements, and optimize resource utilization with precision and ease. Through a thorough analysis, the project identifies existing challenges in the current asset management practices, aiming to not only resolve these issues but also proactively anticipate and mitigate potential risks associated with asset mismanagement, loss, or inefficiencies. Emphasizing user convenience, the system is designed to be intuitive and accessible, ensuring that it meets the practical needs of barangay officials. Integral to the system\'s architecture are stringent access control mechanisms grounded in the CIA Triad principles (Confidentiality, Integrity, and Availability), guaranteeing robust security to protect sensitive data and information input by users, thus fostering a secure and efficient asset management environment for Barangay Santol.', 'Asset inventory management, Threat Mitigation Approach, CIA Triad, Facilities and Equipment.'),
(175, 0, '2024-05', 'BSIT-NS', 'Capstone', 'DEVELOPMENT OF FACILITIES AND EQUIPMENT MANAGEMENT SYSTEM FOR BARANGAY SANTOL', 'ABUNDO, PRECIOUS APPLE - DINI-AY, JONALYN S. - TUSING, LAWRENCE JOHN P.', '', 'The capstone project titled \"Development of Facilities and Equipment Management System for Barangay Santol\" seeks to revolutionize asset management by addressing the urgent need for an efficient tracking and management system for barangay assets, encompassing buildings, equipment, and vehicles. The primary goal is to design and implement a robust, user-friendly system that empowers barangay officials to monitor assets,    schedule maintenance, plan replacements, and optimize resource utilization with precision and ease. Through a thorough analysis, the project identifies existing challenges in the current asset management practices, aiming to not only resolve these issues but also proactively anticipate and mitigate potential risks associated with asset mismanagement, loss, or inefficiencies. Emphasizing user convenience, the system is designed to be intuitive and accessible, ensuring that it meets the practical needs of barangay officials. Integral to the system\'s architecture are stringent access control mechanisms grounded in the CIA Triad principles (Confidentiality, Integrity, and Availability), guaranteeing robust security to protect sensitive data and information input by users, thus fostering a secure and efficient asset management environment for Barangay Santol.', 'Asset inventory management, Threat Mitigation Approach, CIA Triad, Facilities and Equipment.'),
(176, 0, '2024-05', 'BSIT-NS', 'Capstone', 'DEVELOPMENT OF SKYBARANGAY: A CLOUD-BASED BARANGAY MANAGEMENT AND INFORMATION SYSTEM IN WESTERN BICUTAN', 'DADULA, LANCELOT B. - IGNACIO, ANTHONY LOPEZ, GERRY S.', '', 'The Skybarangay system is a comprehensive solution designed to streamline and modernize the processing of barangay documents in Barangay Western Bicutan. Traditionally, the processing of essential documents such as barangay certificates, certificates of indigency, barangay clearances, business permits, and blotter complaints has been handled manually, resulting in long lines and congestion. This project aims to address these challenges by automating and digitizing the procedures in the barangay. The proponents introduced hard-coded security features to protect against malicious users and safeguard sensitive matters within the barangay. To further enhance convenience and ease of access, physical hardware like kiosks will be positioned thoughtfully around the barangay. \"The researchers hope to increase worker productivity and enhance resident satisfaction by putting the Skybarangay system into place. To guarantee the system\'s success, a test plan was established, and an evaluation was carried out with IT professionals, residents, and employees. The evaluation findings revealed a \"\"High\"\" of satisfaction, with a mean score of 3.3. This encouraging feedback demonstrates the Skybarangay system\'s effectiveness in increasing barangay efficiency and improving resident service quality. In conclusion, the Skybarangay system is a huge step forward for Barangay Western Bicutan, providing a more modern and efficient method to handling critical barangay services.\"', 'Barangay Management System, Skybarangay, Kiosk-based Services'),
(177, 0, '2024-05', 'BSIT-NS', 'Capstone', 'ENHANCED SECURED NETWORK WITH ZERO TRUST SECURITY AND CLOUD-BASED BACKUP FOR THE CITY HALL OF MANDALUYONG', 'DELERIO, ALDWIN D. - QUINDOZA, JOHN ANDREW T. - SASIL, MARRIEL B.', '', 'This proposal suggests comprehensive network infrastructure enhancement to boost the reliability and security of Mandaluyong City Hall\'s network. There are currently weaknesses in the system\'s security, frequent periods of unavailability, and the system cannot be scaled up adequately. To solve these problems, this proposal puts forward many technologies and measures for protection, such as port security, high availability failover, centralized management through Active Directory, more robust security with FortiGate Firewall, and cloud-based backup solutions. These improvements aim to enhance integrity within networks, reduce downtimes, and ensure that critical services continue working at all times without interruptions. The survey findings from the project show that most people agree with the effectiveness and suitability of these changes in their organization\'s structure related to information systems management. According to respondents\' comments about control types introduced by this initiative towards improving security levels while minimizing operational times, it can be concluded that success has been realized in terms of making physical access impossible except for authorized personnel, thus reducing risks emanating from unauthorized entry into buildings housing computers or other sensitive data storage devices used within Mandalyong. The proposal suggests that the suggested network upgrades be carried out once verified and implemented because they will help improve s', 'Network Infrastructure Enhancement, Security Improvements, Reliability, Scalability, Port Security, High Availability Failover, Centralized Management'),
(178, 0, '2024-05', 'BSIT-NS', 'Capstone', 'ENHANCEMENT OF TAYTAY YOUTH DEVELOPMENT OFFICE (TYDO) SYSTEM - A SCHOLARSHIP INFORMATION SYSTEM USING MULTI-FACTOR AUTHENTICATION', 'ABUAN, ANDREA T. - BONGALA, ABIGAIL B. - FLORES, CHRISELLE MAE B.', '', 'The capstone project entitled Enhancement of Taytay Youth Development Office (TYDO) System - A Scholarship Information System using Multi-Factor Authentication\"\" aims to modernize and optimize the manual scholarship application and management process of Taytay Municipality, transforming it into a seamless and secure experience for applicants, scholars, and the Taytay Youth Development Office. The study resolved identified issues by proposing a web-based scholarship application system for the Municipality of Taytay, aiming to address inefficiencies, enhance accessibility, improve data security, empower stakeholders, and lay a foundation for future enhancements, ultimately facilitating quicker access to educational opportunities and fostering sustained progress in scholarship management. The methodology details research, technology, and security measures for a web-based scholarship management system, aiming to enhance efficiency, accessibility, and security, while outlining key features to streamline operations. The system features department heads managing reports, internal deputies handling accounts, staff overseeing tasks, and applicants/scholars managing applications. Implemented with security measures like Multi-Factor Authentication and Role-Based Access Control, it ensures quality and user satisfaction.\"', 'using Multi-Factor Authentication, TYDO, Scholars, Applicants, Scholarship process, Scholarship management.'),
(179, 0, '2024-05', 'BSIT-NS', 'Capstone', 'PROPOSED NETWORK SECURITY FOR MARB PRINTING SERVICES', 'ARANETA, JAN LORRY F. - BUENAOBRA, KENNETH JR. I. - DELA VEGA, JOANNE R.', '', 'This study addresses the cybersecurity challenges faced by MARB Printing Services and proposes a network security to enhance protection against cyber threats. The objective is to propose a network security encompassing physical, network, and application security measures for the future expansion of the company. The methodology involves enhancing the existing network with Sophos XG Firewall, Sophos XG DR, and an improved network layout. Utilizing Cisco devices like routers, switches, and network cabling, along with configuring firewalls, VLAN, RIP, TCP, and WAN, ensures the security of critical and confidential information, maintaining the company\'s operational stability.    Additionally, Windows Server 2022 is recommended for centralized user management and secure file storage.    Results indicate that both IT professionals and employees, achieving a composite evaluation mean of 4.04, indicating strong agreement on its effectiveness. Key outcomes include better identification and mitigation of security flaws, enhanced data protection, and efficient traffic management. The continuous surveillance and proactive measures, such as regular alerts and training, contribute to building trust among clients and partners. Recommendations include designing for future expansion, collaborating with cybersecurity experts, adopting new technologies, and developing a comprehensive incident response plan to maintain and enhance security measures as the cybersecurity landscape evolves. This stu', 'Cybersecurity challenges, Network security, Physical security measures, Network security measures, Application security measure.'),
(180, 0, '2024-05', 'BSIT-NS', 'Capstone', 'SAGIP ANI: NURTURING AGRICULTURAL PROSPERITY THROUGH AN E-COMMERCE WEB APPLICATION FOR MARKETING AGRICULTURAL PRODUCTS OF PAKISAMA CONFEDERATION', 'MALABANAN, JAMES B. - RANA, JOSIAH CALEB B. - SALUDES, RAZIA PRINCESS JOY T.', '', 'This study aims to develop a secure web-based e-commerce system for the Pambansang Kilusan ng mga Samahang Magsasaka confederation (PAKISAMA). The system will allow basic e-commerce transactions between customers and admins like purchasing and selling products while securing user data. Asides from the basic features and functionalities that are present on a typical e-commerce system, there are also security features implemented in this study. Security features that are included in this study is Multi-Factor Authentication and bcrypt. Multi-Factor Authentication is a standard security feature implemented on most systems and software applications, it works by verifying the authenticity of a user by requesting a unique one-time pin or OTP sent to their email account upon registering on the system. On the other hand, Bcrypt\'s purpose is to secure data stored in the backend of applications by using a cryptographic hash function that turns a user\'s password into a specific number characters unrecognizable to its original form. The system will be evaluated by using ISO 25010 Product Quality Model Evaluation that assesses a system or software application based on a specific criterion. In this study, the system will be evaluated based on its functionality suitability, interaction capability, reliability, security, and maintainability by three groups. Each group is composed of 10 individuals which are e-commerce platform users, PAKISAMA employees, and IT specialists. The results of the', 'Agriculture, E-commerce, Web Application, Bcrypt, PAKISAMA Confederation, Bcrypt, Security'),
(181, 0, '2024-05', 'BSIT-NS', 'Capstone', 'SECURING AND OPTIMIZING NETWORK THROUGH IPS AND SITE-TO-SITE IPSEC VPN FOR PRICON MICROELECTRONICS', 'CAVAN, DARYL M. - NAVARRO, KYLE DAVID A. - TAMAYO, RODOLF JOHN O.', '', 'The growing reliance on computer networks needs comprehensive cybersecurity measures for companies like Pricon Microelectronics Inc. This project documents the development of an enhanced security solution for Pricon\'s network, which includes Intrusion Prevention Systems (IPS) and a Site-to-Site iPSEC VPN. The project commenced with a thorough assessment of Pricon\'s network environment. This initial phase identified potential security vulnerabilities and evaluated the specific threats Pricon\'s network faced. The risk assessment provided the foundation for selecting the most suitable security solutions. Based on the network security assessment, Intrusion Prevention Systems (IPS) were chosen to actively monitor and block malicious traffic attempting to infiltrate Pricon\'s network. Additionally, a Site-to-Site IPSEC VPN was implemented to establish secure encrypted communication channeis between Pricon\'s locations or with partner networks. The project meticulously details the selection process, configuration, and integration of these security solutions into Pricon\'s existing network infrastructure. Following implementation, rigorous testing procedures were conducted to validate the effectiveness of the IPS and VPN solutions. These tests ensured that the security measures functioned as intended, safeguarding Pricon\'s network from identified threats. The growing reliance on computer networks needs comprehensive cybersecurity measures for companies like Pricon Microelectronics Inc. ', 'Wide Area Network, Local Area Network, Intrusion Prevention System, Site-to-Site IPSec, VPN Tunneling, Virtual Private Network, Enhanced Network Infra'),
(182, 0, '2024-05', 'BSIT-NS', 'Capstone', 'SECURING MICRO IMAGE INTERNATIONAL CORPORATION: A PROPOSED ZERO-TRUST NETWORK ARCHITECTURE FOR DATA PROTECTION AND RISK MITIGATION', 'BANAAG, ADRIAN P. - MAMAYO, SITTIE JANINE D. - VICERA, PAUL JOSHUA L.', '', 'This capstone project proposes a comprehensive Zero Trust Network Architecture (ZTNA) solution to strengthen the security posture of Micro Image International Corporation (MIC). The project addresses the growing security concerns of MIC in light of recent cyber threats. ZTNA significantly improves over traditional perimeter-based security by enforcing continuous authentication of users and devices throughout network sessions. This approach minimizes the potential impact of security breaches by assuming all entities (users, devices, applications) are untrusted. The ZTNA solution leverages Cisco Duo for multi-factor authentication (MFA), adding an extra layer of security to user logins and restricting unauthorized access. Granular access control further tightens security by limiting access to authorized resources only. The solution also encompasses a secure Wide Area Network (WAN) connection for secure data exchange with sister companies. This WAN connection utilizes Fortinet FortiGate firewalls and Site-to-Site VPN to ensure robust data protection. The firewalls provide additional security features like application control, user authentication, and web filtering. The project recommends a phased approach with user training, security policy reviews, and ongoing threat detection practices to ensure successful implementation. The project also emphasizes the importance of vendor selection and equipment compatibility assessment. By implementing the proposed TNA solution and secure W', 'Zero-Trust Network Architecture (TNA), Network Security, Data Protection, Micro Image International Corporation (MIIC), Wide Area Network (WAN), Site-'),
(183, 0, '2024-05', 'BSIT-NS', 'Capstone', 'THE DEVELOPMENT OF ASSISTECH: AN ONLINE HELP DESK FOR MUNICIPALITY OF PATEROS', 'ARIAGA, BETHY MAE S. - CAMILA, MARLON CORNELIO P. - TALAGASYA, BLESSE M.', '', 'Online help desk is implemented in industries to answer inquiries and assist those in need. The Municipality of Pateros struggles to keep up with issues inside the municipality. Considering they have ten barangays with a growing population, the current on-call system might not be reliable since it is prone to altercations. Different departments from the municipality also have concerns that need to be addressed. With those, it can be unorganized and a hassle to deal with. This study aims to develop Assis Tech, an online help desk with an administrator account that can cater to staff and residents\' concerns with their tickets. It also has a chatbot that answers frequently asked questions to minimize the administrator\'s workload and is integrated with two-factor authentication to ensure the system\'s security, preventing unwanted access. This system will increase the municipality\'s accessibility to assist its residents and staff hassle-free, no matter where they are. It also allows users to create accounts, which undergo the process of verification by the administrator. Based on the survey conducted by the researchers using ISO 25010 to evaluate the system, IT Professionals, Employees, and Residents gave excellent remarks in each survey category. The researchers successfully developed the system with the features and security integration. This will encourage the Municipality of Pateros to work on issues and concerns in an organized manner. This system will significantly benefit t', 'Online Help Desk, AssisTech'),
(184, 0, '2024-05', 'BSIT-NS', 'Capstone', 'UNIVIZIT: DEVELOPMENT OF WEB-BASED VISITOR MANAGEMENT SYSTEM AT THE UNIVERSITY OF MAKATI', 'ESPARES, ROI DOMINIC R. - GUILLERMO, KRISTEN JULIEN M. - TOMAS, MARY JOY D.', '', 'Real-time systems in today\'s Computer Technology are very important, and as businesses navigate an Ever-Changing Environment, IT now plays a vital part in designing and improving management systems. The University of Makati was established in 1972, with the envisioned school as an instrument that provides University Education to mold Makati youth as productive citizens. School Safety and Security is crucial for the University to secure important information or data of employee staff and especially the Professors and Students. On top of that, to secure and protect all the technologies, which are the devices of the Professors and Students inside the University. In colleges and universities, the lack of an efficient visitor management system presents a worrying vulnerability, resulting in the unauthorized entry of intruders who may take advantage of the surveillance gap to steal valuable assets. To address the issue, the developers suggest digitizing the visitor handling process and making it more effective with a Web-App that is not only accessible on the Internet but is also responsive to mobile devices.    To Develop a web-based application with Super Admin, Admin, and Visitors as the Main Users. However, in the system, there is a Privileged Account that can create admin accounts, print records of Visitor Information, and have an Auto Archive in their Dashboard. Admin Accounts with Little Privilege such as decrypting the visitor\'s information and approval of the Registration.', 'School Safety, Visitor Management System, Web-Based Visitor Management System'),
(185, 0, '2024-05', 'BSIT-NS', 'Capstone', 'A PROPOSED WEB APPLICATION WITH CLOUD-BASED SECURITY FOR INTEGRATIVE LEARNING CONTENT-BASED SYSTEM FOR SENIOR HIGH SCHOOL STUDENTS OF PRESIDENT DIOSDA', 'ORMIDO, JOHN MARK M.-PAZ, JHET CHRISTIAN V-VIVO, SARAH ERICA D.', '', 'This paper helps you understand and know how to develop an online learning management system from the base with the cloud-based security that is reinforced for an additional layer of security for the system which can give peace of mind to the users of the developed project. With the help of the standards that we are utilizing and using nowadays such as AICC, SCORM, xAPI, and cmi5, the developers successfully developed an online learning management system which is for President Diosdado Macapagal High School, this project is addressing the issues of the users of the President Diosdado Macapagal High School like missing requirements, not accurate recordings, missing paper works and many more. Based on the of the results and summary of findings that has the researchers gathered from testing and interviews, the performance efficiency, the PDMHS-LMS gets a weighted average mean of 4.21, compatibility testing also gets a staggering value of 4.2 weighted average mean. In terms of usability, the PDMHS-LMS has the weighted average mean of 4.31, lastly, reliability, reliability gets a 4.20 weighted average mean. In conclusion the proposed technology PDMHS-LMS is effective and reliable as an alternative solution for the existing problems that is in the President Diosdado Macapagal High School, with this and backed-up by the research results from the interview and research that the researchers performed.', 'Learning management system, cloud security, database, administrator, ISO 25010, modules, dashboard, web-based application, server, database, switches,'),
(186, 0, '2024-05', 'BSIT-NS', 'Capstone', 'AN ENHANCED WIDE AREA NETWORK INFRASTRUCTURE FOR DOST CENTRAL OFFICE: OPTIMIZED FIREWALL AND SYSTEM NETWORK DEPLOYMENT', 'CANONCE, EDRIAN T.-DELICA, CEDRIC JOHN C.-LAGASCA, KAYE M.', '', 'The technology has evolved on how information are exchanged and WANs are the backbone of this interconnected world. However, the complexity of WANs also shows on how organizations expose their security challenges. This research focuses on the development, evaluation and testing of the \\\"Enhanced Wide Area Network Infrastructure for DOST Central Office: Optimized Firewall and System Network Development\\\". The goal was to design an improved wide-area network infrastructure with VPN, redundancy, scalability, and quality of service control. Employing a Descriptive Approach research design, the research incorporated Likert scales administered to IT Professionals. Positive evaluations from the participants emphasized the proposed network infrastructure\\\'s satisfactory in terms of functionality, reliability, usability and security. Therefore, the researchers concluded based on the results, that the proposed network infrastructure function works as intended: access switch, core switch, router and firewall are integrated well. With a total mean score of 4.1 out of 5, the proposed network infrastructure demonstrates that the functionality, reliability and usability of the network infrastructure was rated satisfactory. Overall, these results and findings indicate that the proposed network infrastructure is functional, reliable, usable and secure, making it an effective solution for transferring encrypted data between two DOST branches, offers redundancy, and has a successful connectivit', 'enhanced wide area network infrastructure, WAN, access switch, core switch, router, firewall, IPSec tunnel, redundancy, scalability, VPN, DOST'),
(187, 0, '2024-05', 'BSIT-NS', 'Capstone', 'ASIAN HOSPITAL HEALTH DATA HUB: DEVELOPMENT OF RESEARCH INFORMATION SYSTEM FOR ASIAN HOSPITAL', 'BUENO, REVIN R.-GENERAO, JONAS G.-MEJILLANO, BEA BIANCA R.', '', 'The Hospital Research Information System is a web-based software application tailored for Asian Hospital aimed at modernizing and enhancing the research process within the institution. The Hospital Research Information System aims to digitize and optimize research workflows within Asian Hospital. By leveraging technology, the hospital aims to overcome challenges associated with manual processes. The research design for developing a research information system for Asian Hospital adopts a descriptive approach to address its research process challenges. The study begins with an introduction outlining the need for Enhanced effectiveness and optimized user satisfaction in the research process. A literature review explores successful implementations and challenges faced by similar systems in research settings providing insights to inform the de development process. The study evaluated the web systems functionality, reliability, usability, and security and the results showed that the web system has excellent performance and usability and is reliable and secure. Results of testing reveal that research is reliably recorded and kept in the database and the website is compatible with a range of devices and browsers assuring easy accessibility and operation. And lastly, the results of the evaluation that the Asian Hospital Health Data Hub has been effective in addressing the demands of Asian Hospital needs.', 'Hospital Research Information System, Asian Hospital Health Data Hub'),
(188, 0, '2024-05', 'BSIT-NS', 'Capstone', 'DEVELOPMENT OF A WEB-BASED SEXUALITY EDUCATION PLATFORM FOR ADOLESCENTS', 'BENITEZ, TRIXIE MAY C.-GARCIA, JAHMEL ANDRE C.-GRAMATICA, JULIUS A.', '', 'This paper explores the development and evaluation of a web-based platform for sexuality education, aimed at addressing the lack of comprehensive sexuality education materials in educational institutions. Chapter 1 delves into the background of the issue, highlighting the challenges faced in implementing comprehensive sexuality education in the Philippines. Chapter 2 reviews related literature, providing insights from various studies on sexuality education, online resources, and the effectiveness of web-based programs. In Chapter 5, the study\\\'s findings, conclusions, and recommendations are presented. The findings indicate that the developed web-based platform performed well in terms of performance efficiency, usability, security, functionality, and maintainability, as evaluated based on ISO 25010 standards. Conclusions drawn from the study emphasize the importance of web-based tools in delivering comprehensive sexuality education and the need for continuous improvement in such platforms. Recommendations include adding a summative test and implementing a certification system to enhance student learning and engagement. Overall, this study contributes to addressing the challenges in providing comprehensive sexuality education through innovative technological solutions.', 'Web-based Sexuality Education, Sexuality Education Platform, Learning Management System'),
(189, 0, '2024-05', 'BSIT-NS', 'Capstone', 'DEVELOPMENT OF FACILITIES AND EQUIPMENT MANAGEMENT SYSTEM FOR BARANGAY SANTOL', 'ABUNDO, PRECIOUS APPLE-DINI AY, JONALYN S.-TUSING, LAWRENCE JOHN P.', '', 'The capstone project titled \\\"Development of Facilities and Equipment Management System for Barangay Santol\\\" seeks to revolutionize asset management by addressing the urgent need for an efficient tracking and management system for barangay assets, encompassing buildings, equipment, and vehicles. The primary goal is to design and implement a robust, user-friendly system that empowers barangay officials to monitor assets, schedule maintenance, plan replacements, and optimize resource utilization with precision and ease. Through a thorough analysis, the project identifies existing challenges in the current asset management practices, aiming to not only resolve these issues but also proactively anticipate and mitigate potential risks associated with asset mismanagement, loss, or inefficiencies. Emphasizing user convenience, the system is designed to be intuitive and accessible, ensuring that it meets the practical needs of barangay officials. Integral to the system\\\'s architecture are stringent access control mechanisms grounded in the CIA Triad principles (Confidentiality, Integrity, and Availability), guaranteeing robust security to protect sensitive data and information input by users, thus fostering a secure and efficient asset management environment for Barangay Santol.', 'Asset inventory management, Threat Mitigation Approach, CIA Triad, Facilities and Equipment.'),
(190, 0, '2024-05', 'BSIT-NS', 'Capstone', 'Development of IntelliCam: An Information Management System to Secure Closed-Circuit Television Data', 'ARABACA, WOODY ALLENS G.-BALTAZAR, JOHN AARON R.-CARLOS JR., DELFIN A.', '', 'In the contemporary landscape of surveillance technology, Closed-Circuit Television (CCTV) systems are vital for security in various sectors. This study investigates the vulnerabilities and challenges facing CCTV systems in Barangays Pitogo, Pembo, and West Rembo. Through interviews, concerns such as data overwriting, the need for Two-Factor Authentication (2FA), cloud-based storage vulnerabilities, the importance of a digitally auditable trail, and violence prevention measures are uncovered. A proposed solution aims to address these issues with a tailored approach for each barangay, leveraging advanced security measures and contemporary technologies. The study\\\'s significance lies in strengthening CCTV system security, providing stakeholders like local government, barangay officials, law enforcement, disaster risk reduction offices, and community residents with increased safety and security. The methodology, incorporating Design Thinking and adhering to ISO 25010 standards, ensures the reliability of assessing system pertormance. This literature review also explores the critical aspects of Design Thinking, its integration into organizational culture, its significance in design education, and theoretical foundations, particularly within the constructivist learning theory framework. Ultimately, this research enhances surveillance infrastructure, benefiting both current and future community stakeholders.', 'Closed-Circuit Television (CCTV), Two-Factor Authentication. Cloud-based Storage. Violence prevention, Disaster Risk Reduction, Design Thinking, ISO 2'),
(191, 0, '2024-05', 'BSIT-NS', 'Capstone', 'DEVELOPMENT OF PropertEASE: \\\"A PROPERTY INFORMATION AND SECURITY MANAGEMENT SYSTEM\\\"', 'CHAVEZ, JAN AXCEL V.-GARCIA, MARY JOYCE D.-GARCIA, SHAINE MARIE C.', '', 'The real estate industry faces significant challenges in managing their property-related data. Golden Home Realty relies merely on spreadsheets, which are vulnerable and prone to human errors and Data breaches. As a result of manual input can have severe consequences, underscoring the critical importance of information security. In response, the development of PropertEASE: \\\"A property information and security management system\\\" emerges as a robust web application designed to address these complexities, and it ensures information confidentiality and privacy through multi-factor authentication via email verification, data encryption and system with its database for more secure data storage and quick and easy navigation, allowing them to manage their property information and security more efficiently. The development process involves phases such as planning, system design, development, testing, deployment, and ongoing maintenance. By adhering to these phases, PropertEASE aims to create a robust property information and security management system that meets user needs and delivers value. PropertEASE promises to benefit everyone in the real estate game. Golden Home Realty Dev. Inc. can streamline data management, employees can be more productive, and property owners gain peace of mind. Buyers, sellers, and tenants all win with accurate information and a smoother transaction process. By prioritizing trust and reliability, PropertEASE has the potential to revolutionize the real es', 'Information Security Management System, PropertEASE Management.'),
(192, 0, '2024-05', 'BSIT-NS', 'Capstone', 'ENHANCING BUSINESS CONTINUITY THROUGH VIRTUALIZATION: UTILIZING CLOUD STORAGE AND SYNC FOR DISASTER RECOVERY', 'JOVERES, MICHELLE M.-MALINAO, FLORENCE B.-TAN, CHARLES VINCENT D.', '', 'This research synthesizes a network infrastructure design and configuration plan for Obanana Corp, integrating proactive security protocols and industry best practices. By meticulously addressing specific objectives, including the design of local and wide area networks, implementation of AWS services, and integration of disaster recovery measures, the study aims to enhance organizational resilience and operational efficiency. Proactive measures such as firewall security applications and access management protocols ensure robust network security across multiple floors of the PMI Tower. Rigorous testing and validation procedures validate the reliability and performance of the implemented infrastructure, paving the way for a smooth transition and minimal disruption to operations. By adopting these recommendations, Obana Corp can navigate future technological advancements effectively while safeguarding the integrity and security of its IT infrastructure. Overall, putting these steps into practice will greatly improve Obanana Corp\\\'s technology setup, ensuring strong security, better day-to-day operations, and a solid base for handling future tech changes.', 'Network Infrastructure, AWS Services, Disaster Recovery, Firewall Security Applications, Network Connection, GNS3, Firewall Configuration, Cloud Infra'),
(193, 0, '2024-05', 'BSIT-NS', 'Capstone', 'RISE AND THRIVE: A WEB-BASED PLATFORM TO PROMOTE KALINGA CULTURE, PRODUCTS, AND SERVICES', 'ARIAGA, MA. ANGELICA C.-COLLADO, MARIECOLLE G.-LINESES, KENNETH O.-PIOJO, RAINLYN', '', 'In an age marked by digital connectivity and global trade, the potential of e-commerce to uplift marginalized communities is evident. This study focuses on the development of an e-commerce platform for the indigenous population of Kalinga, Philippines, aimed at promoting their rich cultural heritage and empowering their economic endeavors. The proposed platform, Rise and Thrive, seeks to address the challenges faced by indigenous entrepreneurs, including limited market access and authenticity issues, by providing a dedicated marketplace with features designed to prioritize authenticity, cultural significance, and data security. The significance of this research lies in its pioneering launch of an e-commerce platform tailored specifically for the indigenous population of Kalinga, Philippines. it is for economic empowerment and cultural preservation, the platform offers Kalinga immediate benefits in expanding market reach and connecting with a global audience. By fostering sales growth and positioning Kalinga as a cultural hub, the platform attracts tourism and reinforces the authenticity of indigenous offerings, aside from that it uses technologies such as PHP, HTML, CSS, JavaScript, and MySQL, the platform incorporates measures in security and a payment method to ensure user confidence. Testing and evaluation based on ISO 25010 criteria ensure the platform\\\'s functionality and adherence to standards of confidentiality, integrity, non-repudiation, and accountability. The study', 'Kalinga, E-Commerce, Indigenous Products, Kalinga Culture, Indigenous Website'),
(194, 0, '2024-05', 'BSIT-NS', 'Capstone', 'SAGIP ANI: NURTURING AGRICULTURAL PROSPERITY THROUGH AN E-COMMERCE WEB APPLICATION FOR MARKETING AGRICULTURAL PRODUCTS OF PAKISAMA CONFEDERATION', 'MALABANAN, JAMES B.-RANA, JOSIAH CALEB B.-SALUDES, RAZIA PRINCESS JOY T.', '', 'This study aims to develop a secure web-based e-commerce system for the Pambansang Kilusan ng mga Samahang Magsasaka confederation (PAKISAMA). The system will allow basic e-commerce transactions between customers and admins like purchasing and selling products while securing user data. Asides from the basic features and functionalities that are present on a typical e-commerce system, there are also security features implemented in this study. Security features that are included in this study is Multi-Factor Authentication and bcrypt. Multi-Factor Authentication is a standard security feature implemented on most systems and software applications, it works by verifying the authenticity of a user by requesting a unique one-time pin or OTP sent to their email account upon registering on the system. On the other hand, Bcrypt\\\'s purpose is to secure data stored in the backend of applications by using a cryptographic hash function that turns a user\\\'s password into a specific number characters unrecognizable to its original form. The system will be evaluated by using ISO 25010 Product Quality Model Evaluation that assesses a system or software application based on a specific criterion. In this study, the system will be evaluated based on its functionality suitability, interaction capability, reliability, security, and maintainability by three groups. Each group is composed of 10 individuals which are e-commerce platform users, PAKISAMA employees, and IT specialists. The results of t', 'Agriculture, E-commerce, Web Application, Bcrypt, PAKISAMA Confederation, Bcrypt, Security'),
(195, 0, '2024-05', 'BSIT-NS', 'Capstone', 'THE DEVELOPMENT OF HIVESTOCK: AN ENHANCED SOLUTION FOR THE INVENTORY MANAGEMENT SYSTEM (IMS) OF NIKKA TRADING', 'BARRAMEDA, GINALYN M.-JIMENEZ, CHARINA M.-LABANIEGO, ANGELINE MARIE D.', '', 'The capstone project, \\\"The Development of HiveStock: An Enhanced Solution for the Inventory Management System of Nikka Trading, \\\" is a direct response to the urgent need for a more effective inventory management system. The current system, characterized by manual procedures, obsolete software, and limited visibility, is not only outdated but also poses significant challenges for Nikka Trading. The review of related literature strengthens the proposed study by providing a comprehensive understanding of the current state of knowledge in the field. The study used a descriptive research design to thoroughly examine the project\\\'s objectives and scope, which involved a comprehensive analysis of existing research on inventory management systems, technological advancements, and recent industry developments. Moreover, the evaluation results with a high rating indicate that the system could meet the following ISO 25010 standards, such as its usability and compatibility. With an average total rating of 3.89, interpreted as \\\"Acceptable\\\" in terms of functionality, reliability, performance efficiency, usability, compatibility, security, maintainability, and portability. manual inventory management processes and decentralized spreadsheet reliance further compound the issue, introducing errors and hindering operational efficiency. The proposed solution, a modern inventory management system, offers real-time visibility, streamlined supply chain operations, and strategic integration with ', 'inventory management system, data entry, logistics, technology'),
(196, 0, '2024-05', 'BSIT-NS', 'Capstone', 'VMEME: A SECURED CONTEMPORARY ART GALLERY', 'DUAL, MARIA PAMELLA B.-ERGUIZA, JENDAN KREMLIN C.-NIEVA, SABRINA JOY P.', '', 'The pandemic and technological advancements have propelled e-commerce and online sales to new heights, requiring businesses to adapt and establish a robust digital presence. MEME, an art gallery, recognized this shift but faced limitations with its outdated website. To address this, the researchers developed the MEME: A Contemporary Art Gallery e-commerce website, tailored to enhance their online reach and meet specific needs. The site encompasses essential e-commerce functionalities such as account management, favorites lists, customization options, and QR code payments, along with advanced features like automatic watermarking and artist\\\'s profile management. Ensuring quality and compliance, the website underwent evaluation by art enthusiasts and technology experts guided by the ISO 25010 standards, covering aspects like aesthetics, user experience, security, and accessibility. Employing a descriptive research approach guided by Bhat\\\'s framework, data was collected to understand visitor demographics, interests in contemporary art, and security preferences, enabling the gallery to better cater to its audience. The updated website is fully functional across major browsers, ensuring data security with password protection. It significantly improves on the previous version, seamlessly integrating core e-commerce tools like account management, order processing, and anti-plagiarism measures. Robust cybersecurity protocols, including QR code payments, OTP authentication, and anti-', 'Outdated website, Digital Presence, Ecommerce Website, Automated Watermarking');

-- --------------------------------------------------------

--
-- Table structure for table `theses_backup`
--

CREATE TABLE `theses_backup` (
  `thesis_id` int(4) NOT NULL,
  `archived` tinyint(1) NOT NULL DEFAULT 0,
  `published_date` varchar(7) NOT NULL,
  `course` varchar(100) NOT NULL,
  `category` varchar(20) NOT NULL,
  `title` varchar(150) NOT NULL,
  `authors` varchar(255) NOT NULL,
  `adviser` varchar(100) NOT NULL,
  `abstract` varchar(1500) NOT NULL,
  `keywords` varchar(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `accounts`
--
ALTER TABLE `accounts`
  ADD PRIMARY KEY (`user_id`),
  ADD KEY `user_id` (`user_id`) USING BTREE;

--
-- Indexes for table `theses`
--
ALTER TABLE `theses`
  ADD KEY `thesis_id` (`thesis_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `accounts`
--
ALTER TABLE `accounts`
  MODIFY `user_id` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
